# Generated by Django 3.2.7 on 2021-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
